mod ast;
mod environment;
mod error;
mod evaluator;
mod lexer;
mod parser;
mod token;

use crate::{error::LangError, evaluator::Interpreter, lexer::Lexer, parser::Parser};

/// simply initializes and runs each component in the interpreter.
/// it receives the source code as plain text and passes it through the lexer,
/// then parses it, and finally passes the AST generated by the parser to the evaluator.
/// (the evaluator is the actual runtime of the language, I think I already mentioned this a few times)
///
/// returns `Ok()` if everything went well,
/// any other error from any stage of the interpreter (be it the lexer, parser or actual runtime)
/// is bubbled up to the caller (which is the main function)
pub fn run(code: &str) -> Result<(), LangError> {
    let tokens = Lexer::new(&code).tokenize()?;
    let program = Parser::new(tokens).parse()?;
    Interpreter::new().interpret(&program)?;

    Ok(())
}
