//! I doubt there is much to say about this module
//! it just brings in all the modules and orchestrates the flow of the interpreter

mod ast;
mod environment;
mod error;
mod evaluator;
mod lexer;
mod parser;
mod token;

use std::{env::args, fs, process::ExitCode};

use crate::{error::LangError, evaluator::Interpreter, lexer::Lexer, parser::Parser};

/// simply initializes and runs each component in the interpreter.
/// it receives the source code as plain text and passes it through the lexer,
/// then parses it, and finally passes the AST generated by the parser to the evaluator.
/// (the evaluator is the actual runtime of the language, I think I already mentioned this a few times)
///
/// returns `Ok()` if everything went well,
/// any other error from any stage of the interpreter (be it the lexer, parser or actual runtime)
/// is bubbled up to the caller (which is the main function)
fn run(code: &str) -> Result<(), LangError> {
    let tokens = Lexer::new(&code).tokenize()?;
    let program = Parser::new(tokens).parse()?;
    Interpreter::new().interpret(&program)?;

    Ok(())
}

/// I tried to keep the main function as minimal as possible.
/// it collects the CLI arguments and ensures there is only one (except the program itself).
/// if the provided argument is not a file with the .imi extension, then the program refuses to open the file.
/// if no arguments are provided, it also exits early.
/// if the given argument matches the requirements (one single .imi file),
/// then it will try to open the file and read its contents (exits if it fails to read the file),
/// if we get past everything without an error, then the source code (read from the file) will be
/// passed to the `run()` function.
fn main() -> ExitCode {
    let args: Vec<String> = args().skip(1).collect();

    if args.len() > 1 {
        eprintln!("imi only supports 1 argument.");
        return ExitCode::FAILURE;
    }

    let path = match args.first() {
        Some(p) if p.ends_with(".imi") => p,
        Some(_) => {
            eprintln!("imi only supports .imi files");
            return ExitCode::FAILURE;
        }
        None => {
            eprintln!("usage: imi <file>");
            return ExitCode::FAILURE;
        }
    };

    let code = match fs::read_to_string(path) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("{e}");
            return ExitCode::FAILURE;
        }
    };

    // if at any point the interpreter raises an error,
    // the main function prints it to stderr and exits the program
    if let Err(e) = run(&code) {
        eprintln!("\n{}", e);
        return ExitCode::FAILURE;
    }

    ExitCode::SUCCESS
}
